trigger:
- master
- fix#37

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: BuildAndPack
  displayName: Build and test
  jobs:  
  - job: Build
    displayName: Build and test
    pool:
      vmImage: 'windows-latest'
    steps:
      - task : UseDotNet@2
        displayName: Use dotnet sdk 3.1.x
        inputs:
            packageType: 'sdk'
            version: '3.1.x'

      - task: gitversion/setup@0
        displayName: Install git version
        inputs:
          versionSpec: '5.x'
          includePrerelease: false

      - task: gitversion/execute@0
        displayName: Complete version
        inputs:
          targetPath: '.'

      - task: DotNetCoreCLI@2
        displayName: Build projects
        inputs:
          command: 'build'
          arguments: '-c $(buildConfiguration)'
          versioningScheme: byEnvVar
          versionEnvVar: 'GitVersion.SemVer'

      - task: DotNetCoreCLI@2
        displayName: Test projects
        inputs:
          command: 'test'
          arguments: '-c $(buildConfiguration)'

      - task: DotNetCoreCLI@2
        displayName: Pack packages
        inputs:
          command: 'pack'
          packagesToPack: '**/*.csproj'
          configuration: '$(buildConfiguration)'
          nobuild: true
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'GitVersion.NuGetVersionV2'

      - task: PublishBuildArtifacts@1
        displayName: Push packages to drop
        inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop-azure-ci'
            publishLocation: 'Container'



