trigger:
- master-test
- develop
- release

variables:
  buildConfiguration: 'Release'

stages:
- stage: Windows
  displayName: Build test and pack
  jobs:  
  - job: Build
    displayName: Build test and pack
    pool:
      vmImage: 'windows-latest'
    steps:
      - task : UseDotNet@2
        displayName: Use dotnet sdk 3.1.x
        inputs:
            packageType: 'sdk'
            version: '3.1.x'

      - task: GitVersion/setup@0
        displayName: Install git version
        inputs:
          versionSpec: '5.x'
          includePrerelease: false

      - task: GitVersion/execute@0
        displayName: Complete version
        inputs:
          targetPath: '.'

      - task: DotNetCoreCLI@2
        displayName: Build projects
        inputs:
          command: 'build'
          arguments: '-c $(buildConfiguration) /p:Version=$(GitVersion.AssemblySemVer) /p:FileVersion=$(GitVersion.AssemblySemFileVer)'

      - task: DotNetCoreCLI@2
        displayName: Test projects
        inputs:
          command: 'test'
          arguments: '-c $(buildConfiguration) --no-build'

      - script: |
          export VersionTag=“v”${GitVersion.NuGetVersionV2}
          echo ${VersionTag}

      - task: DotNetCoreCLI@2
        displayName: Pack packages
        inputs:
          command: 'pack'
          packagesToPack: '**/*.csproj'
          nobuild: true
          versioningScheme: 'byEnvVar'
          versionEnvVar: 'GitVersion.NuGetVersionV2'
          verbosityPack: 'Minimal'

      - task: PublishBuildArtifacts@1
        displayName: Push packages to drop
        inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop-azure-ci'
            publishLocation: 'Container'