name: Github actions (Benchmark)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  benchmark:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core 2.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1

    - name: Setup .NET Core 3.1.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Run Benchmark
      run: |
        cd Casbin.Benchmark
        dotnet run -c Release -f netcoreapp31 --join --filter **
